language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람!!
notifications:
  email:
    recipients:
      - kalkin2@naver.com

before_deploy:
  - mkdir -p before-deploy #zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * #bofore-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/modernWeb.zip # deploy로 파일이동

deploy:
  - provider: s3
    access_key_id: AKIAZQQM76XC4JN562G2
    secret_access_key: 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
    bucket: modern-web
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIAZQQM76XC4JN562G2
    secret_access_key: 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
    bucket: modern-web
    key: modernWeb.zip
    bundle_type: zip
    application: modern-web
    deployment_group: modern-web-group
    region: ap-northeast-2
    wait-until-deployed: true

